import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import signalsRouter from "./signals";
import subscriptionsRouter from "./subscriptions";
import paymentsRouter from "./payments";
import mpesaRouter from "./mpesa";
import configRouter from "./config";
import dashboardRouter from "./dashboard";
import mt5Router from "./mt5";
import metaApiWebhookRouter from "./metaapi-webhook";
import copyTradingRouter from "./copy-trading";
import mediaRouter from "./media";
import newsRouter from "./news";
import resourcesRouter from "./resources";
import announcementsRouter from "./announcements";
import pushRouter from "./push";
import referralsRouter from "./referrals";
import journalRouter from "./journal";
import advertisementsRouter from "./advertisements";
import mt5BillingRouter from "./mt5-billing";
import logoRouter from "./logo";
import smtpRouter from "./smtp";
import masterRouter from "./master";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(signalsRouter);
router.use(subscriptionsRouter);
router.use(mpesaRouter);
router.use(paymentsRouter);
router.use(configRouter);
router.use(dashboardRouter);
router.use(mt5Router);
router.use(metaApiWebhookRouter);
router.use(copyTradingRouter);
router.use(mediaRouter);
router.use(newsRouter);
router.use(resourcesRouter);
router.use(announcementsRouter);
router.use(pushRouter);
router.use(referralsRouter);
router.use(journalRouter);
router.use(advertisementsRouter);
router.use(mt5BillingRouter);
router.use(logoRouter);
router.use(smtpRouter);
router.use(masterRouter);

export default router;
